<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6de83cb398d1e2170f89162e856a459a
{
    public static $prefixLengthsPsr4 = array (
        'Q' => 
        array (
            'QuickBooksOnline\\API\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'QuickBooksOnline\\API\\' => 
        array (
            0 => __DIR__ . '/..' . '/quickbooks/v3-php-sdk/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6de83cb398d1e2170f89162e856a459a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6de83cb398d1e2170f89162e856a459a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
